### ISSUE TITLE
Customize PropertyNameTable on JsonEventFormatter

### ISSUE THREAD

**Issue by bencyoung-Fignum** [cloudevents/sdk-csharp#151]
Currently we cant easily set the PropertyNameTable on the JsonTextReader inside the Newtonsoft formatter. As all our events are basically the same it would save us a huge amount of allocations. Adding a virtual base method to create or customize the text reader would be really helpful!

**Comment by jskeet** [comment]
(I'm assuming you're using the current beta, btw. If you're using 1.x at the moment, it's all very different in 2.x :)

Interesting idea... we could make [CreateJsonReader](https://github.com/cloudevents/sdk-csharp/blob/5910e8b34a7cd09ca2499189eef27ffb2330059a/src/CloudNative.CloudEvents.NewtonsoftJson/JsonEventFormatter.cs#L527) virtual (and non-static), but that currently returns `JsonReader` rather than `JsonTextReader`.

We could document (and test) that the default implementation returns a `JsonTextReader`, so that you could call the base method, cast, and then set the property. I think I'd *prefer* not to change the return type of the method to `JsonTextReader`, so that folks could use other `JsonReader` implementations if they want. What do you think?

**Comment by bencyoung-Fignum** [comment]
Yes I'm using the current beta (much nicer already thanks!). Yes I don't mind explicitly casting to JsonTextReader to support my use cases, sounds great

Thanks for the prompt reply.

**Comment by jskeet** [comment]
Cool. Will create a PR for this then. I'll need to check that I actually use CreateJsonReader everywhere, but I *think* I do.

**Comment by jskeet** [comment]
Okay, PR created - including a test which I *believe* is doing what you'd want to do. Could you check that I haven't misunderstood your use case?
