### ISSUE TITLE
Extension attributes should support JSON where data is complex

### ISSUE THREAD

**Issue by chullybun** [cloudevents/sdk-csharp#171]
Maybe I have misunderstood the changes introduced in the latest version.

Previously, we could write an attribute from an object that would be serialized as JSON, versus only supporting primitives such as `string` or `int`; for example:

``` csharp
var ce = new CloudEvent(...);
var ces = ce.GetAttributes();
var obj = new FooBar { Foo = "...", Bar = "..." };
ces.Add("name", obj);  // obj is an instance of a custom class with JSON attributes
```

The latest version has deprecated that functionality, and it looks like attributes must be of type (`CloudEventAttributeType`)[https://github.com/cloudevents/sdk-csharp/blob/master/src/CloudNative.CloudEvents/CloudEventAttributeType.cs] - where an object or JSON is not supported?

Is there a way that I am missing to get this existing behavior?

Thanks.

**Comment by jskeet** [comment]
That's because in CloudEvents spec version 0.3, there was a `Map` attribute type, which was formatted as JSON. That was removed in 1.0 (which is the only version supported by the SDK version 2.0, for simplicity).

It's still fine to have JSON in an attribute value - just convert the value to a string yourself (e.g. with `JsonConvert`), and treat it as an other string-typed attribute.

**Comment by chullybun** [comment]
@jskeet - thanks for the speedy response. After further reading the specification and primer I now understand the motivations of keeping it to simple key/value pairs. I will now revert to this approach. Cheers...
