### ISSUE TITLE
Make CloudEvent not sealed

### ISSUE THREAD

**Issue by bschweizer** [cloudevents/sdk-csharp#176]
With version 1.3.80 it was possible to derive our own implementation from CloudEvent.cs. We used it to create typed events with a generic base class. Example:

```
public abstract class GenericCloudEvent<T> : CloudEvent where T : class, new()
{
    public new T Data
    {
        get => (T)base.Data;
        set => base.Data = value;
    }
}

public class AccountEvent : GenericCloudEvent<AccountEventData>
{
    public AccountEvent(string eventType, Uri source, string subject, DateTime time, string accountId)
        : this(eventType, source, subject, time)
    {
        Data.AccountId = accountId;
    }
}

```

Would it be possible to open CloudEvent again an make it non-sealed?

**Comment by jskeet** [comment]
I would strongly prefer not to do so. It would be a breaking change, for one thing, requiring a new major version. I'm strongly in favour of "design for inheritance or prohibit it". `CloudEvent` is really *not* designed for inheritance. For example, using your generic form, it's still not really safe:

```csharp
CloudEvent evt = new GenericCloudEvent<int>();
evt.Data = "this isn't an integer";
```

Now of course, you could use `GenericCloudEvent` everywhere, never using `CloudEvent` - which would be fine, but in that case you might just as well use composition instead of inheritance, and then nothing can *accidentally* use it as a `CloudEvent` and set the data inappropriately.

**Comment by jskeet** [comment]
Note on compatibility: when I stated before that I'd consider it a breaking change, that's in terms of semantics rather than direct binary or source compatibility. Currently, anyone receiving a `CloudEvent` knows that it's sealed, so they won't receive an instance of a subclass. For example, they could create a new `CloudEvent` based on it, using all the existing properties, and know that it would be complete. That wouldn't be the case if a derived type added more fields. This is much more of a concern with immutable types, of course - unsealing an immutable type is *definitely* breaking.

Unsealing a class isn't explicitly listed in the [MS docs around compatibility](https://docs.microsoft.com/en-us/dotnet/core/compatibility/), and I'm happy to acknowledge that this is a very grey area.

**Comment by bschweizer** [comment]
I see your point and can understand that you don't want to unseal `CloudEvent`. We will adapt our implementation.

**Comment by jskeet** [comment]
Great - thanks very much for your understanding :) Will close this issue now.
