### ISSUE TITLE
Embed license on the nuget package

### ISSUE THREAD

**Issue by mieliespoor** [cloudevents/sdk-csharp#252]
The [nuspec specification](https://github.com/NuGet/Home/wiki/Packaging-License-within-the-nupkg) allows for the license to be specified within the nuspec/csproj files to make it easier to determine which license is being used by the package. 

Could all the package from this repo add this to help making it easier for consumers?

`<license type="expression">Apache-2.0</license>`

**Comment by jskeet** [comment]
Possibly. I know we *don't* do that for Google libraries - there's some disadvantage to using the SPDY identifier instead of embedding the license file directly. I'll look into it; it may not be relevant to CNCF libraries.

**Comment by jskeet** [comment]
Have asked about this. A conservative reading of the license suggests that the license really should be embedded in the package. Unfortunately we can't specify both `<PackageLicenseFile>` and `<PackageLicenseExpression>` in the csproj file (or Directory.Build.props in this particular case).

What I might do is embed the licence file as a regular file within the package, so that we *are* shipping it, but use `<PackageLicenseExpression>` to make the package licensing more machine-readable. Will try to get to that this week.
