### ISSUE TITLE
CloudNative.CloudEvents.AspNetCoreSample will not Auth with Azure Portal

### ISSUE THREAD

**Issue by codeputer** [cloudevents/sdk-csharp#37]
Registering a WebHook in the Azure portal means you have to pass the Authorization test.  This sample code does not allow for it, and hence, not able to be used.

I tried to understand how the OPTION verb is used, which requires CORS to be enabled, as well as a few other challenges.  In the end I decided to create an event subscription to a ServiceBus Queue and read from that.  Likely better for reliability and retry, but again IMO the sample code will not work as it stands today.

CloudEventController.cs, method ReceiveCloudEvent (line 19)

**Comment by clemensv** [comment]
OPTION is a core part of the HTTP spec and is also used with CORS in the exact way as it is used here, but with different header names. Authorization is likely required for the preflight request and since this SDK only maps the CloudEvent onto the request message, it's the client's obligation to add further Authorization info before issuing the request.
